---
title: "GET /v3/partner/health-check"
sidebar_label: "GET /v3/partner/health-check"
description: "GET /v3/partner/health-check"
availableIn: ["dev","alpha","beta","final"]
---

import EndpointDoc from '@site/src/components/EndpointDoc';

export const variants = {"dev":{"method":"GET","path":"/v3/partner/health-check","summary":null,"description":"","deprecated":false,"operationId":"PartnerController_healthCheck[3]_v3","tag":"Partner","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}},"alpha":{"method":"GET","path":"/v3/partner/health-check","summary":null,"description":"","deprecated":false,"operationId":"PartnerController_healthCheck[3]_v3","tag":"Partner","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}},"beta":{"method":"GET","path":"/v3/partner/health-check","summary":null,"description":"","deprecated":false,"operationId":"PartnerController_healthCheck[3]_v3","tag":"Partner","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}},"final":{"method":"GET","path":"/v3/partner/health-check","summary":null,"description":"","deprecated":false,"operationId":"PartnerController_healthCheck[3]_v3","tag":"Partner","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}}};
export const availableIn = ["dev","alpha","beta","final"];

# GET /v3/partner/health-check

<EndpointDoc variants={variants} availableIn={availableIn} />
