---
title: "Get Organization Code"
sidebar_label: "Get Organization Code"
description: "Get organization code"
availableIn: ["dev","alpha","beta","final"]
---

import EndpointDoc from '@site/src/components/EndpointDoc';

export const variants = {"dev":{"method":"GET","path":"/organizations/code","summary":"Get Organization Code","description":"Get organization code","deprecated":false,"operationId":"OrganizationCodeController_getOrganizationCode","tag":"Organization Code Information","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}},"alpha":{"method":"GET","path":"/organizations/code","summary":"Get Organization Code","description":"Get organization code","deprecated":false,"operationId":"OrganizationCodeController_getOrganizationCode","tag":"Organization Code Information","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}},"beta":{"method":"GET","path":"/organizations/code","summary":"Get Organization Code","description":"Get organization code","deprecated":false,"operationId":"OrganizationCodeController_getOrganizationCode","tag":"Organization Code Information","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}},"final":{"method":"GET","path":"/organizations/code","summary":"Get Organization Code","description":"Get organization code","deprecated":false,"operationId":"OrganizationCodeController_getOrganizationCode","tag":"Organization Code Information","parameters":[],"requestBody":null,"responses":{"200":{"description":""},"400":{"description":"The request could not be operated by the server."},"401":{"description":"The resource owner or authorization server denied the request."},"404":{"description":"The requested resource could not be found."},"422":{"description":"The request could not be validated by the server."},"500":{"description":"The server encountered an unexpected condition. Please try again later."}}}};
export const availableIn = ["dev","alpha","beta","final"];

# Get Organization Code

<EndpointDoc variants={variants} availableIn={availableIn} />
